=== 10minutes22/MyOOS/shop/includes/classes/thirdparty/pxw4pa/pXw4Pa.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
	<!ELEMENT pXw4Pa (group)>
	<!ATTLIST pXw4Pa version CDATA "">
	<!ELEMENT group (group*,entry*)+>
	<!ATTLIST group name CDATA "">
	<!ELEMENT entry (#PCDATA)>
	<!ATTLIST entry
		name CDATA ""
		type (boolean|integer|double|string|NULL) "string">

<!--
THIS DTD FILE IS PART OF THE PXW4PA SOFTWARE
AND IT IS RELEASED UNDER THE TERMS OF THE SAME
CC GNU GPL v.2 LICENSE

pXw4Pa - POOR XML WRAPPER FOR PHP ARRAYS v 1.0
Copyright (C) 2005/2006 yayo (Roberto Correzzola)

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty
of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the
Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->

=== 10minutes22/MyOOS/shop/includes/classes/thirdparty/pxw4pa/testcss.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE pXw4Pa SYSTEM "pXw4Pa.dtd">
<?xml-stylesheet type="text/css" href="style1.css"?>
<pXw4Pa version="1.0">
	<group>
		<entry name="key_1" type="string"> v a l u e  2 (html entity and TABs/LFs follow)&#128;

	</entry>
		<entry type="string"> value 2  (some TABs/LFs follow)				
	</entry>
		<entry name="key_2" type="string">value_2bis</entry>
		<entry name="key_3" type="string">value_3</entry>
		<entry name="key_4" type="string">value_4</entry>
		<group name="key_5">
			<entry name="key_A" type="string">value_A</entry>
			<group name="key_B">
				<entry name="key_I" type="string">value_I</entry>
				<entry name="key_II" type="string">value_II</entry>
				<entry type="string">value_III</entry>
				<entry name="key_IV" type="string">value_IV</entry>
				<entry>value_V</entry>
			</group>
		</group>
		<entry name="key_6" type="string">value_6</entry>
		<entry name="key_7" type="string">value_7</entry>
		<group name="key_8">
			<entry name="key_C" type="string">value_C</entry>
			<entry name="key_D" type="string">value_D</entry>
			<entry name="E" type="boolean"></entry>
			<entry name="F" type="boolean">1</entry>
			<entry name="G" type="integer">3</entry>
			<entry name="H" type="double">3.14</entry>
			<entry name="I" type="NULL"/>
		</group>
	</group>
</pXw4Pa>
